version: '0.0.{build}'
image: Visual Studio 2017
init:
  - ps: git config --global core.autocrlf true
install:
  - choco install gitversion.portable -pre -y
assembly_info:
  patch: false
before_build:
  - ps: dotnet --version
  - ps: dotnet restore ./src/Wraptor.sln --verbosity m
  - ps: gitversion /l console /output buildserver
build_script:
  - ps: dotnet publish ./src/Wraptor.sln -c "Release" /p:Version=$env:GitVersion_NuGetVersion /p:Authors="David Szöke"
  - ps: dotnet pack ./src/Wraptor.sln -c "Release" /p:Version=$env:GitVersion_NuGetVersion  /p:Authors="David Szöke"
after_build:
  # For once the build has completed
artifacts:
 - path: './src/Wraptor/bin/Release/netstandard2.0/publish'
 - path: './src/Wraptor/bin/Release/*.nupkg'
on_finish :
  # any cleanup in here
deploy: off
