version: '0.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  - choco install gitversion.portable -pre -y
assembly_info:
  patch: false
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/Wraptor.sln --verbosity m
  - ps: gitversion /l console /output buildserver
build_script:
  - cmd: dotnet publish ./src/Wraptor.sln -c "Release"
after_build:
  # For once the build has completed
artifacts:
 - path: './src/Wraptor/bin/Release/netstandard2.0/publish'
   name: Wraptor
clone_depth: 1
on_finish :
  # any cleanup in here
deploy: off